# Generated by Django 2.2.3 on 2019-07-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parent', models.IntegerField(blank=True, null=True)),
                ('category_name', models.CharField(max_length=100)),
                ('created_user', models.CharField(blank=True, max_length=100, null=True)),
                ('update_user', models.CharField(blank=True, max_length=100, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.IntegerField()),
                ('brands_id', models.IntegerField()),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
    ]
